version: "3.0"
services:
  database:
    image: amsterdam/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: beeldbank
      POSTGRES_USER: beeldbank
      POSTGRES_PASSWORD: insecure
    volumes:
      - databasevolume:/tmp


  importer:
    build: import/
    ports:
      - "8109:8000"
    links:
      - database
    environment:
      - DATAPUNT_API_URL=${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
      - SECRET_KEY=insecure
      - BEELDBANK_DATABASE=beeldbank
      - BEELDBANK_USER=beeldbank
      - BEELDBANK_PASSWORD=insecure
      - BEELDBANK_OBJECTSTORE_PASSWORD
    # nice for testing..
    volumes:
      - $PWD/import/data:/app/data

volumes:
  data-volume:
  databasevolume:


#  api:
#   build: api/
#   ports: 8000
#   links:
#      - database
#   environment:
#      - JWT_SHARED_SECRET_KEY=insecure1234567890
#      - UWSGI_HTTP=0.0.0.0:8000
#      - UWSGI_MODULE=beeldbank.wsgi
#      - UWSGI_CALLABLE=application
#      - UWSGI_MASTER=1
